services:
  server:
    build: .
    environment:
      - DB_LINK_URL=mongodb://user:pass@mongodb
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: bun run --hot src/index.ts
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
